[package]
name = "comparison"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "comparison"
path = "src/main.rs"

[dependencies]
futures = "0.3.31"
regex = "1.11.1"
reqwest = "0.12.15"
scraper = "0.23.1"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
